on: 
  push:
    branches:
      - master

name: 🚀 FTP-deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: ./docs/
        server: mapazmin.ftp.tools
        username: mapazmin_tourguide
        password: ${{ secrets.ftp_password }}
        exclude: .git*
          - .git*/**
          -  **/.git*/**
